// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// runAsyncMultiServer
void runAsyncMultiServer(Environment model, std::string ip, std::string port);
RcppExport SEXP _grpc4bmi_runAsyncMultiServer(SEXP modelSEXP, SEXP ipSEXP, SEXP portSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type ip(ipSEXP);
    Rcpp::traits::input_parameter< std::string >::type port(portSEXP);
    runAsyncMultiServer(model, ip, port);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_grpc4bmi_runAsyncMultiServer", (DL_FUNC) &_grpc4bmi_runAsyncMultiServer, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_grpc4bmi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
