# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Async multi method server
#'
#' @export
runAsyncMultiServer <- function(model, ip = "0.0.0.0", port = "50051") {
    invisible(.Call('_grpc4bmi_runAsyncMultiServer', PACKAGE = 'grpc4bmi', model, ip, port))
}

