# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runServer <- function(model, ip = "0.0.0.0", port = "500051") {
    invisible(.Call('_grpc4bmi_runServer', PACKAGE = 'grpc4bmi', model, ip, port))
}

